# Generated by Django 5.0.2 on 2024-03-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="username",
            field=models.CharField(default="uakks", max_length=100),
        ),
    ]
